### ISSUE TITLE
[SUGGESTION] documentation: how to add fumosay as an alias to linux

### ISSUE THREAD

**Issue by SampersS** [randomtwdude/fumosay#2]
It is a lot of work to go to the fumosay directory and then type ./fumosay instead of just fumosay.
In linux we can add an excecutable as alias so that whenever we type the alias the excecutable gets excecuted (with params).
I figured this out myself, you have to edit /etc/bash.bashrc and paste this line at the end:
alias fumosay='"fumosay directory"/fumosay'
After logging back into the terminal you can just type fumosay "whatever parameters you want" and it will work.
My suggestion is to add this knowledge to the readme.md file so other people don't have to figure this out by themselves.
Maybe you can even add this as an automation in the makefile or an extra script (but you will need sudo to edit bash.bashrc).

**Comment by randomtwdude** [comment]
The next version will have an installation script. Also, I'm not sure, but just putting it in the PATH might be a better choice than aliasing.

**Comment by randomtwdude** [comment]
New version is up with installation scripts (with autotools).
