### ISSUE TITLE
Multibyte characters breaks closing bracket offset

### ISSUE THREAD

**Issue by dmyTRUEk** [randomtwdude/fumosay#4]
For example `fumosay "ΣΣΣ"` makes closing `)` appear earlier than expected.

**Comment by randomtwdude** [comment]
This is a known limitation. Fumos only count bytes. I have some ideas but the real focus is adding fumos at the moment.(I'm tired of writing code, sincerely, a CS student)

**Comment by randomtwdude** [comment]
![image](https://github.com/user-attachments/assets/60897e04-d350-4187-a242-17fc76a96a5c)
Unicode support coming soon(tm).

**Comment by randomtwdude** [comment]
Fixed in version 1.2. (feels good)
